import PDFDocument from 'pdfkit';
import { Board } from '../../infra/database/models/board.ts';

interface CertificateData {
    notation: string;
    bct: number;
    ect: number;
    dimensions: { length: number; width: number; height: number };
    totalCO2: number;
    recycledContent: number;
    isEcoFriendly: boolean;
    auditId?: number;
    date: Date;
    companyName?: string;
}

export class CertificateGenerator {
    
    async generate(data: CertificateData): Promise<Buffer> {
        return new Promise((resolve, reject) => {
            const doc = new PDFDocument({ margin: 50, size: 'A4' });
            const buffers: Buffer[] = [];

            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => resolve(Buffer.concat(buffers)));
            doc.on('error', reject);

            // -- Header --
            this.drawHeader(doc);

            // -- Title --
            doc.moveDown(2);
            doc.font('Helvetica-Bold').fontSize(24).text('Material & Sustainability', { align: 'center' });
            doc.fillColor('#2E7D32').text('CERTIFICATE OF ANALYSIS', { align: 'center' });
            doc.moveDown();

            // -- Box Specifications --
            this.drawSection(doc, 'Product Specifications', 180);
            
            doc.font('Helvetica').fontSize(10).fillColor('black');
            const leftX = 50;
            const rightX = 300;
            let currentY = 210;

            this.drawField(doc, 'Board Notation:', data.notation, leftX, currentY);
            this.drawField(doc, 'Dimensions (LxWxH):', `${data.dimensions.length} x ${data.dimensions.width} x ${data.dimensions.height} mm`, rightX, currentY);
            currentY += 20;
            this.drawField(doc, 'Audit ID:', data.auditId ? `#${data.auditId}` : 'N/A', leftX, currentY);
            this.drawField(doc, 'Date Issued:', data.date.toLocaleDateString(), rightX, currentY);

            // -- Structural Performance --
            this.drawSection(doc, 'Structural Performance', 260);
            currentY = 290;
            
            this.drawField(doc, 'Box Compression Test (BCT):', `${data.bct.toFixed(2)} kgf`, leftX, currentY, true);
            this.drawField(doc, 'Edge Crush Test (ECT):', `${data.ect.toFixed(2)} kN/m`, rightX, currentY);
            
            doc.moveDown(2);
            
            // -- ESG & Sustainability --
            this.drawSection(doc, 'Environmental Impact (ESG)', 340);
            currentY = 370;

            // CO2 Badge
            const co2Color = data.totalCO2 < 0.3 ? '#2E7D32' : (data.totalCO2 < 0.6 ? '#EF6C00' : '#C62828');
            doc.rect(leftX, currentY, 200, 80).fillAndStroke('#F1F8E9', co2Color);
            doc.fillColor(co2Color).fontSize(20).text(`${data.totalCO2.toFixed(3)} kg`, leftX, currentY + 25, { width: 200, align: 'center' });
            doc.fontSize(10).text('CO2e per Box', leftX, currentY + 50, { width: 200, align: 'center' });

            // Recycled Content Badge
            const recycledColor = data.recycledContent > 70 ? '#2E7D32' : '#1565C0';
            doc.rect(rightX, currentY, 200, 80).fillAndStroke('#E3F2FD', recycledColor);
            doc.fillColor(recycledColor).fontSize(20).text(`${data.recycledContent.toFixed(1)}%`, rightX, currentY + 25, { width: 200, align: 'center' });
            doc.fontSize(10).text('Recycled Material Content', rightX, currentY + 50, { width: 200, align: 'center' });

            // Eco Badge
            if (data.isEcoFriendly) {
                doc.image('src/assets/eco-badge-placeholder.png', 480, 50, { width: 60 }).stroke(); // Placeholder
            }

            // -- Footer --
            doc.fontSize(8).fillColor('grey').text(
                'This certificate is system-generated by BoxMetric Intelligence Platform. Calculations are based on TAPPI/ISO standards and theoretical material physics. Actual performance may vary based on conversion quality and environmental conditions.',
                50, 
                700, 
                { align: 'center', width: 500 }
            );

            doc.end();
        });
    }

    private drawHeader(doc: PDFKit.PDFDocument) {
        doc.rect(0, 0, 600, 100).fill('#1A237E'); // Brand Blue
        doc.fontSize(20).fillColor('white').text('BoxMetric', 50, 40);
        doc.fontSize(10).text('Structural Intelligence Engine', 50, 65);
    }

    private drawSection(doc: PDFKit.PDFDocument, title: string, y: number) {
        doc.rect(50, y, 500, 25).fill('#E0E0E0');
        doc.fillColor('#333333').fontSize(12).font('Helvetica-Bold').text(title, 60, y + 7);
    }

    private drawField(doc: PDFKit.PDFDocument, label: string, value: string, x: number, y: number, highlight = false) {
        doc.fontSize(10).font('Helvetica').fillColor('#555555').text(label, x, y);
        doc.font(highlight ? 'Helvetica-Bold' : 'Helvetica').fillColor('black').text(value, x + 120, y);
    }
}
